import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  ar: {
    siteName: "أزاد للأنظمة المتقدمة",
    language: "اللغة",
    arabic: "العربية",
    english: "الإنجليزية",
    searchPlaceholder: "ابحث عن المنتجات...",
    viewAllResults: "عرض كل النتائج",
    searchBy: "البحث حسب :",
    selectCategory: "اختر القسم",
    electronics: "إلكترونيات",
    fashion: "أزياء",
    beauty: "جمال",
    jewelry: "مجوهرات",
    other: "أخرى",
    shopNow: "تسوق الآن",
    jewelryHeroSlide1Subtitle: "مجموعة أزاد الجديدة",
    jewelryHeroSlide1Title: "تألّقي ببريقك كل يوم",
    jewelryHeroSlide2Subtitle: "تصاميم مختارة",
    jewelryHeroSlide2Title: "أناقة تليق بكِ",
    jewelryHeroSlide3Subtitle: "جودة ولمعة",
    jewelryHeroSlide3Title: "تفاصيل تصنع الفرق",
    jewelryHeroSlide4Subtitle: "هدايا مميزة",
    jewelryHeroSlide4Title: "اختاري هدية تبقى",
    jewelryHeroDesc: "قطع مختارة بعناية بتفاصيل أنيقة ولمعة فاخرة.",
    jewelryAboutSubtitle: "مجموعة يونيتي",
    jewelryAboutTitle: "تسوق تعاونياتنا محدودة الإصدار",
    jewelryAboutDescLine1: "هذا نص تجريبي يمكن استبداله بمحتوى حقيقي لاحقًا.",
    jewelryAboutDescLine2: "استخدمه لوصف المجموعة أو الشراكات أو العروض الخاصة.",
    jewelryNav1Line1: "خواتم",
    jewelryNav1Line2: "وأقراط",
    jewelryNav2Line1: "أساور",
    jewelryNav2Line2: "وغوايش",
    jewelryNav3Line1: "قلادات",
    jewelryNav3Line2: "متدلية",
    jewelryNav4Line1: "قلادات",
    jewelryNav4Line2: "ألماس",
    jewelryHeroImageAlt: "صورة سلايدر",
    allCategories: "كل الأقسام",
    contactUs: "تواصل معنا",
    currency: "العملة",
    currencyILS: "الشيقل",
    currencyJOD: "الدينار الأردني",
    currencyUSD: "الدولار",
    currencyAED: "الدرهم الإماراتي",
    currencySAR: "الريال السعودي",
    setting: "الإعدادات",
    myProfile: "ملفي",
    wishlist: "المفضلة",
    cart: "السلة",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    hello: "مرحباً",
    helloUser: "مرحباً، {name}",
    yourAccount: "حسابك",
    error: "حدث خطأ",
    noProducts: "لا توجد منتجات",
    shopByCategory: "تسوق حسب الفئة",
    shopByMostPopular: "تسوق حسب الأكثر رواجاً",
    mostPopularInStore: "الأكثر رواجاً في المتجر",
    startingFrom: "ابتداءً من",
    productNotAvailableCurrently: "هذا المنتج غير متوفر حالياً",
    pleaseLoginFirst: "يرجى تسجيل الدخول أولاً",
    submitReviewFailed: "فشل إرسال التقييم",
    yourRating: "تقييمك:",
    commentRequired: "التعليق مطلوب",
    writeYourReviewHere: "اكتب تقييمك هنا...",
    send: "إرسال",
    sendComment: "إرسال تعليق",
    followers: "متابع",
    hotline: "الخط الساخن",
    menu: "القائمة",
    toggleSubmenu: "تبديل القائمة الفرعية",
    home: "الرئيسية",
    homeTwo: "الرئيسية 2",
    homeThree: "الرئيسية 3",
    homeFour: "الرئيسية 4",
    shop: "المتجر",
    shopGrid: "شبكة المتجر",
    shopRightSidebar: "شريط جانبي يمين",
    shopHiddenSidebar: "شريط جانبي مخفي",
    cartPage: "سلة التسوق",
    shoppingCart: "سلة التسوق",
    checkout: "الدفع",
    compare: "المقارنة",
    wishlist: "المفضلة",
    loginPage: "تسجيل الدخول",
    registerPage: "إنشاء حساب",
    forgotPassword: "نسيت كلمة المرور",
    resetPassword: "إعادة تعيين كلمة المرور",
    couponPage: "الكوبونات",
    blog: "المدونة",
    blogGrid: "شبكة المدونة",
    blogList: "قائمة المدونة",
    blogDetails: "تفاصيل المقال",
    contact: "تواصل معنا",
    searchPage: "بحث المنتجات",
    shopCategory: "تسوق حسب التصنيف",
    productDetails: "تفاصيل المنتج",
    notFound: "غير موجود",
    couponGrabBestOffer: "احصل على أفضل عرض",
    errorGeneric: "حدث خطأ",
    noProductsFound: "لا توجد منتجات",
    noBrandsFound: "لا توجد علامات تجارية",
    noCategoryFound: "لا توجد تصنيفات",
    noCouponsFound: "لا توجد كوبونات",
    loading: "جاري التحميل",
    showingResults: "عرض {from}–{to} من أصل {total} نتيجة",
    loadMore: "تحميل المزيد",
    noSearchMatchesStart: "عذرًا، لا توجد نتائج تطابق",
    noSearchMatchesEnd: "ضمن كلمات البحث",
    mostPopular: "الأكثر رواجاً",
    sortByPrice: "ترتيب حسب السعر",
    priceLowToHigh: "السعر من الأقل للأعلى",
    priceHighToLow: "السعر من الأعلى للأقل",
    defaultSorting: "الترتيب الافتراضي",
    lowToHigh: "من الأقل للأعلى",
    highToLow: "من الأعلى للأقل",
    newAdded: "الأحدث",
    onSale: "عروض",
    filter: "تصفية",
    priceFilter: "تصفية السعر",
    categories: "التصنيفات",
    colors: "الألوان",
    status: "الحالة",
    resetFilter: "إعادة ضبط التصفية",
    close: "إغلاق",
    previous: "السابق",
    next: "التالي",
    pageXofY: "صفحة {page} من {total}",
    cancel: "إلغاء",
    save: "حفظ",
    saving: "جاري الحفظ...",
    saveChanges: "حفظ التغييرات",
    actions: "إجراءات",
    role: "الدور",
    nameLabel: "الاسم",
    emailLabel: "البريد الإلكتروني",
    passwordLabel: "كلمة المرور",
    phoneLabel: "رقم الهاتف",
    phoneRequired: "رقم الهاتف مطلوب",
    addressRequired: "العنوان مطلوب",
    bioRequired: "النبذة مطلوبة",
    nameRequired: "الاسم مطلوب",
    emailRequired: "البريد الإلكتروني مطلوب",
    emailInvalid: "البريد الإلكتروني غير صالح",
    siteSettings: "إعدادات الموقع",
    tabGeneral: "عام",
    tabContact: "التواصل",
    tabPayment: "الدفع",
    tabSocial: "روابط التواصل",
    tabBackup: "نسخة احتياطية",
    siteNameLabel: "اسم الموقع",
    siteUrlLabel: "رابط الموقع",
    faviconUrlLabel: "رابط الأيقونة",
    ogImageUrlLabel: "رابط صورة المشاركة",
    metaTitleLabel: "عنوان الميتا",
    metaDescriptionLabel: "وصف الميتا",
    footerTextLabel: "نص الفوتر",
    defaultDeliveryChargeLabel: "رسوم التوصيل الافتراضية",
    standardDeliveryChargeLabel: "رسوم التوصيل (عادي)",
    expressDeliveryChargeLabel: "رسوم التوصيل (سريع)",
    freeShippingMinSubtotalLabel: "حد الشحن المجاني (قيمة السلة)",
    bundleDiscountEnabledLabel: "تفعيل خصم الباقة",
    bundleDiscountPercentLabel: "نسبة خصم الباقة (%)",
    bundleDiscountMinItemsLabel: "أقل عدد قطع لتفعيل الخصم",
    giftWrapEnabledLabel: "تفعيل تغليف الهدايا",
    giftWrapFeeStandardLabel: "رسوم التغليف العادي",
    giftWrapFeePremiumLabel: "رسوم التغليف الفاخر",
    whatsappNumberLabel: "رقم واتساب",
    whatsappDefaultMessageLabel: "رسالة واتساب الافتراضية",
    deliveryEstimateMinDaysLabel: "أقل مدة توصيل (أيام)",
    deliveryEstimateMaxDaysLabel: "أقصى مدة توصيل (أيام)",
    shippingCostTiersLabel: "شرائح رسوم التوصيل (JSON)",
    invalidJson: "صيغة JSON غير صحيحة",
    enableCod: "تفعيل الدفع عند الاستلام",
    enableCard: "تفعيل الدفع بالبطاقة",
    enablePaypal: "تفعيل الدفع عبر PayPal",
    enableBankTransfer: "تفعيل التحويل البنكي",
    bankTransferInstructionsLabel: "تعليمات التحويل البنكي",
    backupInfo: "قم بتنزيل نسخة احتياطية أو استعادة نسخة سابقة.",
    downloadBackupTitle: "تنزيل نسخة احتياطية",
    downloadBackupDesc: "قم بتنزيل ملف نسخة احتياطية للاحتفاظ به.",
    downloadNow: "تنزيل الآن",
    restoreBackupTitle: "استعادة نسخة احتياطية",
    restoreBackupDesc: "ارفع ملف النسخة الاحتياطية لاستعادة البيانات.",
    uploadRestoreFile: "رفع ملف للاستعادة",
    restoring: "جاري الاستعادة...",
    backupDownloadedSuccess: "تم تنزيل النسخة الاحتياطية بنجاح",
    backupDownloadedFailed: "فشل تنزيل النسخة الاحتياطية",
    backupRestoredSuccess: "تمت الاستعادة بنجاح",
    backupRestoredFailed: "فشلت الاستعادة",
    settingsUpdatedSuccess: "تم تحديث الإعدادات بنجاح",
    settingsUpdatedFailed: "فشل تحديث الإعدادات",
    logoAlt: "الشعار",
    faviconAlt: "الأيقونة",
    ogImageAlt: "صورة المشاركة",
    passwordRequired: "كلمة المرور مطلوبة",
    passwordMin6: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    termsRequired: "يجب الموافقة على الشروط والأحكام للمتابعة.",
    passwordMin6Placeholder: "على الأقل 6 أحرف",
    leaveBlankToKeepPassword: "اتركه فارغاً للإبقاء على القديمة",
    rememberMe: "تذكرني",
    forgotPasswordQuestion: "نسيت كلمة المرور؟",
    loginSuccess: "تم تسجيل الدخول بنجاح",
    loginButton: "تسجيل الدخول",
    registerButton: "إنشاء حساب",
    createAccount: "إنشاء حساب",
    signInWithGoogle: "تسجيل الدخول عبر Google",
    googleAuthSetupError: "حدث خطأ في إعداد تسجيل الدخول عبر Google",
    createAccountFailed: "فشل إنشاء الحساب",
    resetLinkButton: "إرسال رابط الاستعادة",
    resetLinkFailed: "فشل إرسال رابط الاستعادة",
    agreeTermsPrefix: "أوافق على",
    and: "و",
    termsOfService: "شروط الخدمة",
    privacyPolicyLink: "سياسة الخصوصية",
    createAccountSuccess: "تم إنشاء الحساب بنجاح",
    alreadyHaveAccountQuestion: "لديك حساب بالفعل؟",
    dontHaveAccountQuestion: "ليس لديك حساب؟",
    createFreeAccount: "أنشئ حساباً مجانياً",
    orCreateAccountVia: "أو أنشئ حساباً عبر",
    orLoginVia: "أو سجل عبر",
    resetYourPassword: "أعد تعيين كلمة المرور",
    confirmPasswordLabel: "تأكيد كلمة المرور",
    confirmPasswordPlaceholder: "تأكيد كلمة المرور",
    confirmPasswordAction: "تأكيد كلمة المرور",
    passwordsMustMatch: "كلمتا المرور غير متطابقتين",
    confirmPasswordRequired: "تأكيد كلمة المرور مطلوب",
    resetPasswordFailed: "فشل إعادة تعيين كلمة المرور",
    adminLoginPageTitle: "تسجيل دخول المسؤول",
    adminPanelTitle: "لوحة تحكم المسؤول",
    dashboardTotalSales: "إجمالي المبيعات",
    dashboardTotalOrders: "إجمالي الطلبات",
    dashboardPendingOrders: "الطلبات المعلقة",
    dashboardProcessingOrders: "الطلبات قيد التنفيذ",
    dashboardCompletedOrders: "الطلبات المكتملة",
    dashboardWelcome: "مرحباً بك في لوحة التحكم. استخدم القائمة الجانبية للتنقل بين أقسام النظام المختلفة.",
    add: "إضافة",
    edit: "تعديل",
    delete: "حذف",
    visit: "زيارة",
    noLogo: "لا يوجد شعار",
    manageBrands: "إدارة العلامات التجارية",
    addBrand: "إضافة علامة تجارية",
    editBrand: "تعديل العلامة التجارية",
    brandLogo: "الشعار",
    logoUrlLabel: "رابط الشعار",
    websiteLabel: "الموقع الإلكتروني",
    locationLabel: "الموقع",
    descriptionLabel: "الوصف",
    manageCategories: "إدارة التصنيفات",
    addCategory: "إضافة تصنيف",
    editCategory: "تعديل التصنيف",
    deleteCategoryConfirmText: "لن تتمكن من استرجاع هذا التصنيف!",
    categoryUpdatedSuccess: "تم تحديث التصنيف بنجاح",
    categoryAddedSuccess: "تم إضافة التصنيف بنجاح",
    categoryDeletedSuccess: "تم حذف التصنيف بنجاح.",
    noImage: "لا يوجد صورة",
    noCategoriesFound: "لا توجد تصنيفات حالياً",
    statusVisible: "ظاهر",
    statusHidden: "مخفي",
    categoryImage: "الصورة",
    categoryParentLabel: "اسم التصنيف",
    categoryParentRequired: "اسم التصنيف مطلوب",
    productTypeLabel: "نوع المنتج",
    productTypeRequired: "نوع المنتج مطلوب",
    selectProductType: "اختر النوع...",
    subcategoriesLabel: "التصنيفات الفرعية",
    subcategoriesPlaceholder: "مثال: ذهب, فضة, ألماس",
    subcategoriesHelp: "أدخل الأسماء مفصولة بفاصلة (،) أو (,)",
    imageUrlLabel: "رابط الصورة",
    loadingDataError: "حدث خطأ في تحميل البيانات",
    imageUrlInvalid: "يجب أن يكون رابط الصورة صحيحاً",
    websiteUrlInvalid: "يجب أن يكون الرابط صحيحاً",
    brandUpdatedSuccess: "تم تحديث العلامة التجارية بنجاح",
    brandAddedSuccess: "تم إضافة العلامة التجارية بنجاح",
    deleteBrandConfirmText: "لن تتمكن من استرجاع هذه العلامة التجارية!",
    brandDeletedSuccess: "تم حذف العلامة التجارية بنجاح.",
    adminMainMenu: "القائمة الرئيسية",
    adminDashboard: "لوحة التحكم",
    adminProducts: "المنتجات",
    adminOrders: "الطلبات",
    adminCategories: "التصنيفات",
    adminBrands: "العلامات التجارية",
    adminCoupons: "الكوبونات",
    adminReviews: "التقييمات",
    adminReports: "التقارير",
    adminUsers: "المستخدمين",
    adminSettings: "الإعدادات",
    adminLogout: "تسجيل الخروج",
    manageUsers: "إدارة المستخدمين",
    manageProducts: "إدارة المنتجات",
    addNewUser: "إضافة مستخدم جديد",
    editUser: "تعديل مستخدم",
    newUserPasswordRequired: "كلمة المرور مطلوبة للمستخدم الجديد",
    joinDate: "تاريخ الانضمام",
    noUsers: "لا يوجد مستخدمين",
    roleAdmin: "مسؤول",
    roleUser: "مستخدم",
    statusActive: "نشط",
    statusInactive: "غير نشط",
    statusBlocked: "محظور",
    confirmTitle: "هل أنت متأكد؟",
    deleteUserConfirmText: "لن تتمكن من استرجاع هذا المستخدم!",
    yesDelete: "نعم، احذفه!",
    deleted: "تم الحذف!",
    userDeletedSuccess: "تم حذف المستخدم بنجاح.",
    deleteError: "حدث خطأ أثناء الحذف",
    updateUserSuccess: "تم تعديل المستخدم بنجاح",
    addUserSuccess: "تم إضافة المستخدم بنجاح",
    productDeleteConfirm: "هل أنت متأكد من حذف هذا المنتج؟",
    productDeletedSuccess: "تم حذف المنتج بنجاح",
    productDeleteFailed: "فشل حذف المنتج",
    adminAddProduct: "إضافة منتج",
    productImage: "صورة",
    productName: "اسم المنتج",
    stock: "المخزون",
    loadingDots: "جاري التحميل...",
    adminLoginSuccess: "تم تسجيل الدخول كمسؤول بنجاح",
    adminLoginFailed: "فشل تسجيل الدخول",
    couponCodeRequiredError: "يرجى إدخال رمز الكوبون",
    couponInvalidError: "يرجى إدخال كوبون صحيح",
    couponExpiredError: "هذا الكوبون غير صالح",
    couponMinimumError: "الحد الأدنى {amount} لتطبيق هذا الكوبون",
    couponAppliedMessage: "تم تطبيق كوبون {title} على {productType}",
    somethingWentWrong: "حدث خطأ ما",
    cardPaymentSetupFailed: "فشل تجهيز الدفع بالبطاقة.",
    paymentMethodNotEnabledCard: "خيار الدفع بالبطاقة غير مُفعل حالياً.",
    paymentMethodNotEnabledCod: "خيار الدفع عند الاستلام غير مُفعل حالياً.",
    paymentMethodNotEnabledPaypal: "خيار PayPal غير مُفعل حالياً.",
    paymentMethodNotEnabledBankTransfer: "خيار التحويل البنكي غير مُفعل حالياً.",
    cardPaymentNotAvailable: "الدفع بالبطاقة غير متاح حالياً.",
    orderConfirmed: "تم تأكيد طلبك!",
    orderStatus_pending: "قيد المراجعة",
    orderStatus_processing: "قيد التجهيز",
    orderStatus_delivered: "تم التسليم",
    orderStatus_cancel: "ملغي",
    paymentFailed: "فشل إتمام الدفع.",
    noOrdersYet: "لا يوجد طلبات بعد",
    brand: "العلامات التجارية",
    popularBrands: "أشهر العلامات",
    topRatedProducts: "الأعلى تقييماً",
    filterByColor: "تصفية حسب اللون",
    addToCart: "أضف للسلة",
    viewCart: "عرض السلة",
    addToWishlist: "أضف للمفضلة",
    addToCompare: "أضف للمقارنة",
    quickView: "عرض سريع",
    addedToCartToast: "تم إضافة {quantity} من {title} إلى السلة",
    removedFromCartToast: "تم إزالة {title} من السلة",
    noMoreQuantityAvailable: "لا توجد كمية إضافية متاحة لهذا المنتج",
    confirmClearCart: "هل أنت متأكد أنك تريد إزالة جميع العناصر؟",
    addedToWishlistToast: "تم إضافة {title} إلى المفضلة",
    removedFromWishlistToast: "تم إزالة {title} من المفضلة",
    addedToCompareToast: "تم إضافة {title} إلى المقارنة",
    removedFromCompareToast: "تم إزالة {title} من المقارنة",
    compareProducts: "مقارنة",
    buyNow: "اشتر الآن",
    quantity: "الكمية",
    color: "اللون",
    reviews: "مراجعات",
    review: "مراجعة",
    seeMore: "عرض المزيد",
    seeLess: "عرض أقل",
    outOfStock: "غير متوفر",
    inStock: "متوفر",
    onlyXLeft: "متبقي {count} فقط",
    askQuestion: "اسأل سؤالاً",
    subtotal: "المجموع الفرعي",
    shipping: "الشحن",
    shippingCost: "تكلفة الشحن",
    discount: "الخصم",
    total: "الإجمالي",
    proceedToCheckout: "الانتقال للدفع",
    freeShipping: "شحن مجاني",
    securePayment: "دفع آمن",
    flatRate: "سعر ثابت",
    localPickup: "استلام محلي",
    cartEmpty: "سلة التسوق فارغة",
    wishlistEmpty: "قائمة المفضلة فارغة",
    compareEmpty: "قائمة المقارنة فارغة",
    clearCart: "إفراغ السلة",
    recommendedAddons: "إضافات مقترحة",
    goToShop: "اذهب إلى المتجر",
    addMoreForFreeShipping: "أضف {amount} للحصول على شحن مجاني",
    eligibleForFreeShipping: "أنت مؤهل للشحن المجاني",
    yourOrder: "طلبك",
    product: "المنتج",
    description: "الوصف",
    price: "السعر",
    rating: "التقييم",
    messageLabel: "الرسالة",
    subjectLabel: "الموضوع",
    subjectRequired: "الموضوع مطلوب",
    messageRequired: "الرسالة مطلوبة",
    fullNamePlaceholder: "اسمك الكامل",
    subjectPlaceholder: "اكتب عنوان الموضوع",
    messagePlaceholder: "اكتب رسالتك هنا...",
    consentText: "أوافق على حفظ بياناتي في هذا المتصفح لاستخدامها لاحقاً.",
    consentRequired: "الموافقة مطلوبة",
    sendMessageSuccess: "تم إرسال الرسالة بنجاح",
    remove: "إزالة",
    action: "إجراء",
    noDescription: "لا يوجد وصف",
    amount: "المبلغ",
    orderId: "رقم الطلب",
    orderTime: "وقت الطلب",
    view: "عرض",
    invoice: "فاتورة",
    paymentMethod: "طريقة الدفع",
    noPaymentMethodsEnabled: "لا توجد طرق دفع مفعلة حالياً.",
    paypalPaymentNote: "سيتم تأكيد الدفع عبر PayPal بعد إنشاء الطلب.",
    bankTransferManualPayment: "تحويل بنكي / دفع يدوي",
    shippingOptionRequired: "خيار الشحن مطلوب",
    paymentOptionRequired: "خيار الدفع مطلوب",
    cashOnDelivery: "الدفع عند الاستلام",
    creditCard: "بطاقة ائتمان",
    placeOrder: "إتمام الطلب",
    deliveryToday: "توصيل اليوم",
    deliverySevenDays: "توصيل خلال 7 أيام",
    deliveryEstimate: "تقدير التوصيل",
    deliveryEstimateDaysRange: "{min}–{max} أيام",
    giftWrap: "تغليف هدية",
    addGiftWrap: "أضف تغليف هدية",
    giftWrapStandard: "تغليف عادي",
    giftWrapPremium: "تغليف فاخر",
    giftWrapMessagePlaceholder: "اكتب رسالة قصيرة للهدية (اختياري)",
    giftWrapFee: "رسوم التغليف",
    bundleDiscount: "خصم الباقة",
    quickConsultation: "استشارة سريعة عبر واتساب",
    featuredReviews: "مراجعات مختارة",
    customer: "عميل",
    sizeGuide: "دليل المقاسات",
    sizeGuideRingTitle: "الخاتم",
    sizeGuideRingDesc: "قيسي محيط الإصبع بخيط أو شريط ورقي، حددي القياس بالميليمتر ثم قارنيه بجدول المقاسات. إذا كنتِ بين مقاسين اختاري الأكبر.",
    sizeGuideBraceletTitle: "السوار",
    sizeGuideBraceletDesc: "قيسي محيط المعصم وأضيفي 1–2 سم للراحة. للسوار الضيق اختاري المقاس الأقرب، وللسوار الفضفاض زيدي أكثر قليلاً.",
    sizeGuideNecklaceTitle: "السلسال",
    sizeGuideNecklaceDesc: "اختاري الطول حسب الإطلالة: 40–45 سم قريب من الرقبة، 50–60 سم على الصدر. جرّبي بخيط لتحديد الطول الأنسب.",
    askAboutSize: "اسأل عن المقاس",
    askAboutMaterial: "اسأل عن المادة/الذهب",
    askAboutAvailability: "اسأل عن التوفر",
    whatsappQuestionGeneral: "أريد استشارة سريعة عن هذا المنتج.",
    whatsappQuestionSize: "أحتاج مساعدة في اختيار المقاس المناسب.",
    whatsappQuestionMaterial: "ما هي مادة المنتج/نوع الذهب والطلاء؟",
    whatsappQuestionAvailability: "هل المنتج متوفر الآن؟ وما مدة التجهيز؟",
    coupon: "كوبون",
    apply: "تطبيق",
    couponCode: "رمز الكوبون",
    haveCoupon: "هل لديك كوبون؟",
    clickToEnterCode: "اضغط لإدخال الرمز",
    search: "بحث",
    searchByLabel: "البحث حسب",
    allDepartments: "كل الأقسام",
    freeExpressShipping: "شحن سريع مجاني للطلبات فوق {amount}",
    footerDesc: "متجر إلكتروني عربي لتجربة تسوق سهلة وآمنة.",
    myAccount: "حسابي",
    personalDetails: "البيانات الشخصية",
    enterUsername: "أدخل اسم المستخدم",
    enterYourEmail: "أدخل بريدك الإلكتروني",
    enterYourNumber: "أدخل رقمك",
    enterYourAddress: "أدخل عنوانك",
    enterYourBio: "أدخل نبذة عنك",
    updateProfile: "تحديث الحساب",
    updateProfileFailed: "فشل تحديث الحساب",
    phoneMin11: "رقم الهاتف يجب أن يكون 11 رقمًا على الأقل",
    bioMin20: "النبذة يجب أن تكون 20 حرفًا على الأقل",
    oldPassword: "كلمة المرور القديمة",
    newPassword: "كلمة المرور الجديدة",
    oldPasswordRequired: "كلمة المرور القديمة مطلوبة",
    newPasswordRequired: "كلمة المرور الجديدة مطلوبة",
    changePasswordFailed: "فشل تغيير كلمة المرور",
    update: "تحديث",
    trackOrders: "تتبع الطلبات",
    shippingPolicy: "الشحن",
    orderHistory: "سجل الطلبات",
    returns: "الاستبدال والاسترجاع",
    info: "معلومات",
    ourStory: "قصتنا",
    careers: "الوظائف",
    privacyPolicy: "سياسة الخصوصية",
    terms: "الشروط والأحكام",
    whatsapp: "واتساب",
    facebook: "فيسبوك",
    sendMessage: "أرسل رسالة",
    stayInTouch: "ابقَ على تواصل معنا",
    followUsOnSocialMedia: "تابعنا على وسائل التواصل",
    aboutIntro: "أزاد للأنظمة المتقدمة منصة تهدف لتقديم منتجات مختارة بعناية وتجربة شراء سهلة وآمنة. نركز على الجودة وخدمة العملاء وتطوير تجربة الاستخدام باستمرار.",
    aboutVisionTitle: "رؤيتنا",
    aboutVisionDesc: "أن نكون وجهتك المفضلة للتسوق عبر الإنترنت عبر توفير منتجات متنوعة وخدمة موثوقة.",
    aboutValuesTitle: "قيمنا",
    aboutValue1: "الشفافية والوضوح في الأسعار والسياسات.",
    aboutValue2: "الجودة في المنتجات والتغليف والتسليم.",
    aboutValue3: "دعم سريع واحترافي عند الحاجة.",
    aboutContactPrefix: "لأي استفسار أو اقتراح، يسعدنا تواصلك عبر",
    aboutContactLink: "صفحة تواصل معنا",
    contactPage: "صفحة تواصل معنا",
    careersIntro: "نبحث دائمًا عن أشخاص شغوفين لتحسين تجربة التسوق وخدمة العملاء. إذا رغبت بالانضمام لفريقنا، أرسل سيرتك الذاتية ومجال اهتمامك.",
    careersHowToApplyTitle: "كيف تتقدم",
    careersStep1: "اكتب عنوان الرسالة: “وظائف - {siteName}”.",
    careersStep2: "أرفق السيرة الذاتية ورابط أعمالك إن وجد.",
    careersStep3: "اذكر المدينة وأوقات التفرغ ومجال الخبرة.",
    careersContactTitle: "التواصل",
    careersContactPrefix: "أرسل طلبك عبر",
    privacyIntro: "توضح سياسة الخصوصية هذه كيفية جمع واستخدام وحماية معلوماتك عند استخدامك لموقع {siteName}. باستخدامك للموقع، فإنك توافق على الممارسات الموضحة أدناه.",
    privacyInfoWeCollectTitle: "المعلومات التي نجمعها",
    privacyInfoWeCollect1: "معلومات الحساب: الاسم، البريد الإلكتروني، رقم الهاتف.",
    privacyInfoWeCollect2: "معلومات الطلبات: المنتجات، عنوان الشحن، تفاصيل الفاتورة.",
    privacyInfoWeCollect3: "معلومات تقنية: عنوان IP، نوع المتصفح، سجلات الاستخدام.",
    privacyHowWeUseTitle: "كيف نستخدم معلوماتك",
    privacyHowWeUse1: "معالجة الطلبات وتأكيدها وخدمة ما بعد البيع.",
    privacyHowWeUse2: "التواصل معك بخصوص الطلبات أو الدعم الفني.",
    privacyHowWeUse3: "تحسين تجربة المستخدم وأداء الموقع.",
    privacySharingTitle: "مشاركة المعلومات",
    privacySharingDesc: "لا نبيع معلوماتك الشخصية. قد نشارك بيانات محدودة مع مزودي خدمات موثوقين (مثل شركات الشحن أو الدفع) بالقدر اللازم لتقديم الخدمة.",
    privacySecurityTitle: "حماية البيانات",
    privacySecurityDesc: "نطبق إجراءات أمنية مناسبة للمساعدة في حماية بياناتك، ومع ذلك لا يمكن ضمان الأمان الكامل عبر الإنترنت.",
    privacyRightsTitle: "حقوقك",
    privacyRightsPrefix: "يمكنك طلب تحديث أو حذف بيانات حسابك أو الاستفسار عن بياناتك عبر صفحة",
    returnsIntro: "هدفنا رضاك التام. توضح هذه السياسة شروط الإرجاع والاستبدال والخطوات المطلوبة لطلب ذلك.",
    returnsConditionsTitle: "شروط الإرجاع",
    returnsCondition1: "يجب أن يكون المنتج بحالته الأصلية وغير مستخدم.",
    returnsCondition2: "يرجى الاحتفاظ بالفاتورة أو رقم الطلب.",
    returnsCondition3: "قد لا تشمل السياسة بعض المنتجات حسب طبيعتها.",
    returnsStepsTitle: "خطوات تقديم طلب إرجاع/استبدال",
    returnsStep1: "تواصل معنا وأرسل رقم الطلب وسبب الإرجاع.",
    returnsStep2: "سيتم تزويدك بتعليمات الشحن/التسليم حسب الحالة.",
    returnsStep3: "بعد الاستلام والفحص، يتم إتمام الإرجاع أو الاستبدال.",
    returnsRefundTitle: "الاسترداد",
    returnsRefundDesc: "يتم استرداد المبلغ وفق طريقة الدفع المستخدمة وبعد اعتماد الإرجاع. قد تستغرق العملية عدة أيام عمل حسب مزود الدفع.",
    returnsContactTitle: "التواصل",
    returnsContactPrefix: "لبدء طلب إرجاع/استبدال، استخدم",
    shippingIntro: "نعمل على شحن الطلبات بأسرع وقت ممكن. هذه السياسة توضّح آلية تجهيز الطلبات وخيارات الشحن والتسليم.",
    shippingPreparationTitle: "تجهيز الطلب",
    shippingPreparation1: "يتم تجهيز الطلب بعد تأكيد الدفع.",
    shippingPreparation2: "قد تختلف مدة التجهيز حسب توفر المنتج وعدد الطلبات.",
    shippingDeliveryTimesTitle: "أوقات التسليم",
    shippingDeliveryTimes1: "المدة تقديرية وتختلف حسب المنطقة.",
    shippingDeliveryTimes2: "قد تحدث تأخيرات بسبب الظروف اللوجستية أو الطقس.",
    shippingCostTitle: "تكلفة الشحن",
    shippingCostDesc: "تظهر تكلفة الشحن (إن وجدت) أثناء إتمام عملية الشراء حسب العنوان وطريقة التوصيل.",
    shippingTrackTitle: "تتبع الطلب",
    shippingTrackPrefix: "يمكنك متابعة حالة طلبك من صفحة",
    shippingTrackLink: "الحساب",
    termsIntro: "تحكم هذه الشروط والأحكام استخدامك لموقع {siteName} وعمليات الشراء عبره. باستخدامك للموقع أو إجراء طلب، فإنك توافق على هذه الشروط.",
    termsOrdersPaymentTitle: "الطلبات والدفع",
    termsOrdersPayment1: "قد يتم إلغاء الطلب في حال تعذر تأكيد الدفع أو توفر المنتج.",
    termsOrdersPayment2: "الأسعار قابلة للتحديث، ويتم تثبيت السعر عند تأكيد الطلب.",
    termsShippingDeliveryTitle: "الشحن والتسليم",
    termsShippingDeliveryDescPrefix: "أوقات التسليم تقديرية وقد تختلف حسب المنطقة والظروف التشغيلية. لمزيد من التفاصيل راجع صفحة",
    termsReturnsTitle: "الإرجاع والاستبدال",
    termsReturnsDescPrefix: "تخضع عمليات الإرجاع والاستبدال للسياسة المعتمدة. راجع صفحة",
    termsIpTitle: "الملكية الفكرية",
    termsIpDesc: "جميع المحتويات (نصوص، صور، شعارات) مملوكة لأزاد للأنظمة المتقدمة أو مرخصة لها ولا يجوز استخدامها دون إذن.",
    termsContactTitle: "التواصل",
    termsContactPrefix: "لأي استفسار حول هذه الشروط، تواصل معنا عبر",
    latestNews: "آخر الأخبار",
    contactUsSmall: "تواصل معنا",
    haveQuestionCall: "لديك استفسار؟ اتصل بنا",
    copyright: "© {year} أزاد للأنظمة المتقدمة",
    addressLocation: "رام الله فلسطين",
    share: "مشاركة:",
    easyReturns: "إرجاع سهل خلال 30 يومًا",
    sameDayDispatch: "اطلب قبل 2:30م للشحن في نفس اليوم",
    secureCheckoutLine1: "دفع آمن",
    secureCheckoutLine2: "وموثوق",
    subscribe: "اشترك",
    subscribeDesc: "اشترك لتصلك أحدث العروض والمنتجات",
    enterEmail: "أدخل بريدك الإلكتروني",
    followUsOn: "تابعنا على",
    pageNotFoundTitle: "عذرًا! الصفحة غير موجودة",
    pageNotFoundDesc: "الصفحة التي تبحث عنها غير موجودة.",
    backToHome: "العودة إلى الرئيسية",
    dealOfDay: "صفقة اليوم",
    viewAllDeals: "عرض جميع العروض",
    productCollection: "مجموعة المنتجات",
    discoverOurProducts: "اكتشف منتجاتنا",
    viewNow: "اعرض الآن",
    products: "منتجات",
    allCollection: "كل المجموعات",
    bracelets: "أساور",
    necklaces: "قلائد",
    earrings: "أقراط",
    withNewLookCollection: "بمظهر جديد ومجموعة جديدة",
    spotlightProductTitle: "منتج مميز",
    spotlightProductDesc: "اكتشف التفاصيل داخل المجموعة.",
    buildYourOwnSets: "كوّن مجموعتك الخاصة",
    ourFinestJewelry: "أفخر مجوهراتنا",
    shopThisCollection: "تسوق هذه المجموعة",
    bestSellerThisWeek: "الأكثر مبيعًا هذا الأسبوع",
    weeksFeatured: "مميز هذا الأسبوع",
    shopAllProducts: "تسوق كل المنتجات",
    moreToDiscover: "المزيد لاكتشافه",
    trendingArrivals: "الوافدون الجدد الأكثر رواجًا",
    trendingBannerTitleLine1: "تونيك بأكمام قصيرة",
    trendingBannerTitleLine2: "قَصّة كاجوال مريحة",
    exploreMore: "استكشف المزيد",
    newArrivalsTitle: "وصل حديثًا",
    trendingProducts: "منتجات رائجة",
    tabNew: "جديد",
    tabFeatured: "مميز",
    tabTopSellers: "الأكثر مبيعًا",
    trendingThisWeek: "الرائج هذا الأسبوع",
    specialProducts: "منتجات مميزة",
    enjoyBestQuality: "استمتع بأفضل جودة",
    tabTrending: "رائج",
    tabBeauty: "جمال",
    tabCosmetics: "مستحضرات التجميل",
    topSellersForYou: "الأكثر مبيعًا لأجلك",
    bestSellersInBeauty: "الأكثر مبيعًا في قسم الجمال",
    shopByFeatured: "تسوق حسب المميز",
    discountProducts: "منتجات مخفّضة",
    featuredProducts: "منتجات مميزة",
    sellingProducts: "الأكثر مبيعًا",
    selectedNoveltyLine1: "منتجات مختارة",
    selectedNoveltyLine2: "جديدة",
    topRatedLine1: "الأعلى تقييمًا",
    topRatedLine2: "منتجات",
    onlyPrice: "فقط {price}",
    electronicsGadgetsLine1: "إلكترونيات",
    electronicsGadgetsLine2: "وأجهزة",
    moreProducts: "المزيد من المنتجات",
    sale20OffAllStore: "خصم 20% على كل المتجر",
    sale35Off: "خصم 35%",
    subscribeNewsletter: "اشترك في نشرتنا البريدية",
    bannerSmartphoneLine1: "هاتف ذكي",
    bannerSmartphoneLine2: "BLU G91 Pro 2022",
    bannerHyperXLine1: "HyperX Cloud II",
    bannerHyperXLine2: "لاسلكي",
    startingAt: "ابتداءً من",
    bestTabletCollection2023: "أفضل مجموعة تابلت 2023",
    bestNotebookCollection2023: "أفضل مجموعة لابتوب 2023",
    exclusiveOffer: "عرض حصري",
    offThisWeek: "هذا الأسبوع",
    palHeroBadge1: "مجموعة جديدة",
    palHeroBadge2: "إصدار محدود",
    palHeroBadge3: "هدايا من القلب",
    palHeroTitle1: "ذهب يليق بكِ",
    palHeroTitle2: "حكاية كوفية… بروح عصرية",
    palHeroTitle3: "هدية تحمل معنى",
    palHeroText1a: "لمسات مستوحاة من",
    palHeroText1b: "فلسطين",
    palHeroText1c: "بتصميم عالمي",
    palHeroText2a: "تفاصيل دقيقة،",
    palHeroText2b: "أصالة",
    palHeroText2c: "على الترند",
    palHeroText3a: "تغليف أنيق ولمسة",
    palHeroText3b: "حمراء",
    palHeroText3c: "تشد الانتباه",
    nextDayProducts: "منتجات اليوم التالي",
    relatedProducts: "منتجات ذات صلة",
    bundleSubtitle: "أكملي إطلالتك",
    completeYourLook: "كوّني طقمك",
    bundleDiscountHint: "خصم Bundle: {percent}% عند شراء {minItems}+ قطع (يُطبق عند الدفع)",
    faqShippingQuestion: "كم مدة التوصيل؟",
    faqShippingAnswer: "التوصيل عادة خلال {min}–{max} أيام عمل حسب المنطقة وتوفر المنتج.",
    faqReturnsQuestion: "هل يوجد إرجاع أو تبديل؟",
    faqReturnsAnswer: "نعم، إرجاع/تبديل خلال {days} يومًا وفق سياسة المتجر.",
    faqSizeQuestion: "كيف أختار المقاس المناسب؟",
    faqSizeAnswer: "استخدمي دليل المقاسات في صفحة المنتج أو تواصلي معنا عبر واتساب للمساعدة.",
    recentlyViewedSubtitle: "شوهدت مؤخراً",
    recentlyViewed: "منتجات شاهدتها مؤخراً",
    collection: "مجموعة",
    collections: "المجموعات",
    collectionsSubtitle: "اختاري من تشكيلاتنا",
    collectionsTitle: "تسوّقي المجموعات",
    trending: "رائج",
    newArrival: "وصل حديثًا",
    jewelryBannerTitle1Line1: "أصداف أرديكو",
    jewelryBannerTitle1Line2: "خواتم 2023",
    jewelryBannerTitle2: "طقم استوائي",
    jewelryBannerTitle3: "مجوهرات ذهبية",
    jewelryBannerFullTitleLine1: "خاتم ذهب",
    jewelryBannerFullTitleLine2: "مع ألماس",
    cosmeticsCollection: "مجموعة مستحضرات التجميل",
    foundationAndPowderBrushLine1: "فرشاة فاونديشن",
    foundationAndPowderBrushLine2: "وبودرة",
    discoverNow: "اكتشف الآن",
    topsBlouseShirtsLine1: "توبات",
    topsBlouseShirtsLine2: "بلوزات و قمصان",
    shopCollection: "تسوق المجموعة",
    beautySelectionOffer: "اكتشف مجموعتنا من الجمال {discount} من أجلك...",
    beautySelectionDiscount: "خصم إضافي 75%",
    day: "يوم",
    hrs: "ساعة",
    min: "دقيقة",
    sec: "ثانية",
    flashSaleEndsIn: "ينتهي عرض الفلاش خلال:",
    off: "خصم",
    active: "نشط",
    inactive: "غير نشط",
    copied: "تم النسخ!",
    couponTooltipPart1: "*سيتم تطبيق كود الكوبون على",
    couponTooltipCategory: "منتجات البقالة",
    couponTooltipPart2: "وعند التسوق بقيمة أعلى من",
    sku: "SKU",
    tag: "وسم",
    twitter: "تويتر",
    linkedin: "لينكدإن",
    vimeo: "فيميو",
    paymentOptions: "خيارات الدفع",
    orderDetails: "تفاصيل الطلب",
    invoiceId: "رقم الفاتورة",
    date: "التاريخ",
    serial: "م",
    print: "طباعة",
    thankYouOrderReceived: "شكرًا لك {name}، تم استلام طلبك!",
    authenticityCardTitle: "بطاقة الأصالة",
    authenticityQrAlt: "رمز QR للتحقق من الأصالة",
    scanToVerifyOnWhatsapp: "امسحي رمز QR للتحقق عبر واتساب",
    verifyOnWhatsapp: "تحقق عبر واتساب",
    authenticityWhatsappMessage: "مرحباً، أريد التحقق من أصالة الطلب رقم {invoice}.",
    reviewsAreIn: "التقييمات وصلت",
    customersReview: "آراء العملاء",
    whatClientsSay: "ماذا يقول عملاؤنا",
    coFounder: "شريك مؤسس",
    uiUxDesigner: "مصمم UI/UX",
    webDeveloper: "مطور ويب",
    fashionTestimonial1: "“يمكنك استخدام اسم المدينة أو البلدة كما تشاء. يمكن استخدام النتائج بحرية في أي عمل.”",
    fashionTestimonial2: "“سعداء جداً بخيارنا. كان الفريق رائعاً بالكامل! شكراً لكم!”",
    fashionTestimonial3: "“شكراً لجهودكم وروح الفريق خلال الأشهر الماضية! شكراً جزيلاً.”",
    beautyTestimonial1: "تجربة ممتازة وجودة رائعة وخدمة سريعة. أنصح بها.",
    beautyTestimonial2: "منتجات جميلة وتفاصيل دقيقة، وتجربة شراء مريحة.",
    beautyTestimonial3: "تغليف أنيق ودفع آمن وتوصيل سريع. تجربة ممتازة.",
  },
  en: {
    siteName: "Azad Advanced Systems",
    language: "Language",
    arabic: "Arabic",
    english: "English",
    searchPlaceholder: "Search for products...",
    viewAllResults: "View all results",
    searchBy: "Search by :",
    selectCategory: "Select Category",
    electronics: "Electronics",
    fashion: "Fashion",
    beauty: "Beauty",
    jewelry: "Jewelry",
    other: "Other",
    shopNow: "Shop Now",
    jewelryHeroSlide1Subtitle: "Azad New Collection",
    jewelryHeroSlide1Title: "Shine every day",
    jewelryHeroSlide2Subtitle: "Curated Designs",
    jewelryHeroSlide2Title: "Elegance that suits you",
    jewelryHeroSlide3Subtitle: "Quality & Sparkle",
    jewelryHeroSlide3Title: "Details that make a difference",
    jewelryHeroSlide4Subtitle: "Special Gifts",
    jewelryHeroSlide4Title: "Choose a gift that lasts",
    jewelryHeroDesc: "Carefully selected pieces with elegant details and a luxurious shine.",
    jewelryAboutSubtitle: "Unity Collection",
    jewelryAboutTitle: "Shop our limited Edition Collaborations",
    jewelryAboutDescLine1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    jewelryAboutDescLine2: "Cras vel mi quam. Fusce vehicula vitae mauris sit amet tempor. Donec consectetur lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
    jewelryNav1Line1: "Rings",
    jewelryNav1Line2: "& Earrings",
    jewelryNav2Line1: "Bracelets",
    jewelryNav2Line2: "& Bangles",
    jewelryNav3Line1: "Pendant",
    jewelryNav3Line2: "Necklaces",
    jewelryNav4Line1: "Diamond",
    jewelryNav4Line2: "Necklaces",
    jewelryHeroImageAlt: "Slider image",
    allCategories: "All Categories",
    contactUs: "Contact Us",
    currency: "Currency",
    currencyILS: "Israeli Shekel",
    currencyJOD: "Jordanian Dinar",
    currencyUSD: "US Dollar",
    currencyAED: "UAE Dirham",
    currencySAR: "Saudi Riyal",
    setting: "Setting",
    myProfile: "My Profile",
    wishlist: "Wishlist",
    cart: "Cart",
    login: "Login",
    logout: "Logout",
    hello: "Hello,",
    helloUser: "Hello, {name}",
    yourAccount: "Your Account",
    error: "There was an error",
    noProducts: "No products found",
    followers: "Followers",
    hotline: "Hotline",
    menu: "Menu",
    toggleSubmenu: "Toggle submenu",
    home: "Home",
    homeTwo: "Home Two",
    homeThree: "Home Three",
    homeFour: "Home Four",
    shop: "Shop",
    shopGrid: "Shop Grid",
    shopRightSidebar: "Shop Right Sidebar",
    shopHiddenSidebar: "Shop Hidden Sidebar",
    cartPage: "Cart",
    shoppingCart: "Shopping Cart",
    checkout: "Checkout",
    compare: "Compare",
    wishlist: "Wishlist",
    loginPage: "Login",
    registerPage: "Register",
    forgotPassword: "Forgot Password",
    resetPassword: "Reset Password",
    couponPage: "Coupons",
    blog: "Blog",
    blogGrid: "Blog Grid",
    blogList: "Blog List",
    blogDetails: "Blog Details",
    contact: "Contact",
    searchPage: "Search Products",
    shopCategory: "Shop Category",
    productDetails: "Product Details",
    notFound: "Not Found",
    couponGrabBestOffer: "Grab Best Offer",
    errorGeneric: "There was an error",
    noProductsFound: "No products found",
    shopByCategory: "Shop by category",
    shopByMostPopular: "Shop by most popular",
    mostPopularInStore: "Most popular in store",
    startingFrom: "Starting from",
    productNotAvailableCurrently: "This product is currently unavailable",
    pleaseLoginFirst: "Please log in first",
    submitReviewFailed: "Failed to submit review",
    yourRating: "Your rating:",
    commentRequired: "Comment is required",
    writeYourReviewHere: "Write your review here...",
    send: "Send",
    sendComment: "Send comment",
    noBrandsFound: "No brands found",
    noCategoryFound: "No categories found",
    noCouponsFound: "No coupons found",
    loading: "Loading",
    showingResults: "Showing {from}–{to} of {total} results",
    loadMore: "Load More",
    noSearchMatchesStart: "Sorry, nothing matched",
    noSearchMatchesEnd: "search terms",
    mostPopular: "Most Popular",
    sortByPrice: "Sort By Price",
    priceLowToHigh: "Price low to high",
    priceHighToLow: "Price high to low",
    defaultSorting: "Default Sorting",
    lowToHigh: "Low to High",
    highToLow: "High to Low",
    newAdded: "New Added",
    onSale: "On Sale",
    filter: "Filter",
    priceFilter: "Price Filter",
    categories: "Categories",
    colors: "Colors",
    status: "Status",
    resetFilter: "Reset Filter",
    close: "Close",
    previous: "Previous",
    next: "Next",
    pageXofY: "Page {page} of {total}",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving...",
    saveChanges: "Save Changes",
    actions: "Actions",
    role: "Role",
    nameLabel: "Name",
    emailLabel: "Email",
    passwordLabel: "Password",
    phoneLabel: "Phone",
    phoneRequired: "Phone is required",
    addressRequired: "Address is required",
    bioRequired: "Bio is required",
    nameRequired: "Name is required",
    emailRequired: "Email is required",
    emailInvalid: "Invalid email",
    siteSettings: "Site Settings",
    tabGeneral: "General",
    tabContact: "Contact",
    tabPayment: "Payment",
    tabSocial: "Social",
    tabBackup: "Backup",
    siteNameLabel: "Site Name",
    siteUrlLabel: "Site URL",
    faviconUrlLabel: "Favicon URL",
    ogImageUrlLabel: "OG Image URL",
    metaTitleLabel: "Meta Title",
    metaDescriptionLabel: "Meta Description",
    footerTextLabel: "Footer Text",
    defaultDeliveryChargeLabel: "Default Delivery Charge",
    standardDeliveryChargeLabel: "Standard Delivery Charge",
    expressDeliveryChargeLabel: "Express Delivery Charge",
    freeShippingMinSubtotalLabel: "Free shipping minimum subtotal",
    bundleDiscountEnabledLabel: "Enable bundle discount",
    bundleDiscountPercentLabel: "Bundle discount percent (%)",
    bundleDiscountMinItemsLabel: "Minimum items for bundle discount",
    giftWrapEnabledLabel: "Enable gift wrap",
    giftWrapFeeStandardLabel: "Standard gift wrap fee",
    giftWrapFeePremiumLabel: "Premium gift wrap fee",
    whatsappNumberLabel: "WhatsApp number",
    whatsappDefaultMessageLabel: "Default WhatsApp message",
    deliveryEstimateMinDaysLabel: "Minimum delivery days",
    deliveryEstimateMaxDaysLabel: "Maximum delivery days",
    shippingCostTiersLabel: "Shipping cost tiers (JSON)",
    invalidJson: "Invalid JSON format",
    enableCod: "Enable cash on delivery",
    enableCard: "Enable card payment",
    enablePaypal: "Enable PayPal",
    enableBankTransfer: "Enable bank transfer",
    bankTransferInstructionsLabel: "Bank transfer instructions",
    backupInfo: "Download a backup or restore a previous one.",
    downloadBackupTitle: "Download Backup",
    downloadBackupDesc: "Download a backup file to keep it safe.",
    downloadNow: "Download Now",
    restoreBackupTitle: "Restore Backup",
    restoreBackupDesc: "Upload a backup file to restore your data.",
    uploadRestoreFile: "Upload restore file",
    restoring: "Restoring...",
    backupDownloadedSuccess: "Backup downloaded successfully",
    backupDownloadedFailed: "Failed to download backup",
    backupRestoredSuccess: "Backup restored successfully",
    backupRestoredFailed: "Failed to restore backup",
    settingsUpdatedSuccess: "Settings updated successfully",
    settingsUpdatedFailed: "Failed to update settings",
    logoAlt: "Logo",
    faviconAlt: "Favicon",
    ogImageAlt: "OG image",
    passwordRequired: "Password is required",
    passwordMin6: "Password must be at least 6 characters",
    termsRequired: "You must agree to continue.",
    passwordMin6Placeholder: "Min. 6 characters",
    leaveBlankToKeepPassword: "Leave it blank to keep the current one",
    rememberMe: "Remember me",
    forgotPasswordQuestion: "Forgot password?",
    loginSuccess: "Login successful",
    loginButton: "Login",
    registerButton: "Register",
    createAccount: "Create account",
    signInWithGoogle: "Sign in with Google",
    googleAuthSetupError: "Something went wrong with Google sign-in setup",
    createAccountFailed: "Failed to create account",
    resetLinkButton: "Send reset link",
    resetLinkFailed: "Failed to send reset link",
    agreeTermsPrefix: "I agree to the",
    and: "and",
    termsOfService: "Terms of Service",
    privacyPolicyLink: "Privacy Policy",
    createAccountSuccess: "Account created successfully",
    alreadyHaveAccountQuestion: "Already have an account?",
    dontHaveAccountQuestion: "Don't have an account?",
    createFreeAccount: "Create a free account",
    orCreateAccountVia: "Or create an account via",
    orLoginVia: "Or sign in via",
    resetYourPassword: "Reset your password",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm Password",
    confirmPasswordAction: "Confirm password",
    passwordsMustMatch: "Passwords must match",
    confirmPasswordRequired: "Confirm password is required",
    resetPasswordFailed: "Failed to reset password",
    adminLoginPageTitle: "Admin Login",
    adminPanelTitle: "Admin Panel",
    dashboardTotalSales: "Total Sales",
    dashboardTotalOrders: "Total Orders",
    dashboardPendingOrders: "Pending Orders",
    dashboardProcessingOrders: "Processing Orders",
    dashboardCompletedOrders: "Completed Orders",
    dashboardWelcome: "Welcome to the dashboard. Use the sidebar to navigate between different system sections.",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    visit: "Visit",
    noLogo: "No logo",
    manageBrands: "Brand Management",
    addBrand: "Add Brand",
    editBrand: "Edit Brand",
    brandLogo: "Logo",
    logoUrlLabel: "Logo URL",
    websiteLabel: "Website",
    locationLabel: "Location",
    descriptionLabel: "Description",
    manageCategories: "Category Management",
    addCategory: "Add Category",
    editCategory: "Edit Category",
    deleteCategoryConfirmText: "You won't be able to recover this category!",
    categoryUpdatedSuccess: "Category updated successfully",
    categoryAddedSuccess: "Category added successfully",
    categoryDeletedSuccess: "Category deleted successfully.",
    noImage: "No image",
    noCategoriesFound: "No categories found",
    statusVisible: "Visible",
    statusHidden: "Hidden",
    categoryImage: "Image",
    categoryParentLabel: "Category Name",
    categoryParentRequired: "Category name is required",
    productTypeLabel: "Product Type",
    productTypeRequired: "Product type is required",
    selectProductType: "Select type...",
    subcategoriesLabel: "Subcategories",
    subcategoriesPlaceholder: "Example: Gold, Silver, Diamond",
    subcategoriesHelp: "Enter names separated by comma (,)",
    imageUrlLabel: "Image URL",
    loadingDataError: "There was an error loading the data",
    imageUrlInvalid: "Please enter a valid image URL",
    websiteUrlInvalid: "Please enter a valid URL",
    brandUpdatedSuccess: "Brand updated successfully",
    brandAddedSuccess: "Brand added successfully",
    deleteBrandConfirmText: "You won't be able to recover this brand!",
    brandDeletedSuccess: "Brand deleted successfully.",
    adminMainMenu: "Main Menu",
    adminDashboard: "Dashboard",
    adminProducts: "Products",
    adminOrders: "Orders",
    adminCategories: "Categories",
    adminBrands: "Brands",
    adminCoupons: "Coupons",
    adminReviews: "Reviews",
    adminReports: "Reports",
    adminUsers: "Users",
    adminSettings: "Settings",
    adminLogout: "Logout",
    manageUsers: "User Management",
    manageProducts: "Product Management",
    addNewUser: "Add New User",
    editUser: "Edit User",
    newUserPasswordRequired: "Password is required for a new user",
    joinDate: "Join Date",
    noUsers: "No users found",
    roleAdmin: "Admin",
    roleUser: "User",
    statusActive: "Active",
    statusInactive: "Inactive",
    statusBlocked: "Blocked",
    confirmTitle: "Are you sure?",
    deleteUserConfirmText: "You won't be able to recover this user!",
    yesDelete: "Yes, delete it!",
    deleted: "Deleted!",
    userDeletedSuccess: "User deleted successfully.",
    deleteError: "An error occurred while deleting",
    updateUserSuccess: "User updated successfully",
    addUserSuccess: "User added successfully",
    productDeleteConfirm: "Are you sure you want to delete this product?",
    productDeletedSuccess: "Product deleted successfully",
    productDeleteFailed: "Failed to delete product",
    adminAddProduct: "Add Product",
    productImage: "Image",
    productName: "Product Name",
    stock: "Stock",
    loadingDots: "Loading...",
    adminLoginSuccess: "Logged in as admin successfully",
    adminLoginFailed: "Login failed",
    couponCodeRequiredError: "Please enter a coupon code",
    couponInvalidError: "Please enter a valid coupon",
    couponExpiredError: "This coupon is not valid",
    couponMinimumError: "Minimum {amount} required to apply this coupon",
    couponAppliedMessage: "Your coupon {title} is applied on {productType}",
    somethingWentWrong: "Something went wrong",
    cardPaymentSetupFailed: "Failed to set up card payment.",
    paymentMethodNotEnabledCard: "Card payment is not enabled right now.",
    paymentMethodNotEnabledCod: "Cash on delivery is not enabled right now.",
    paymentMethodNotEnabledPaypal: "PayPal is not enabled right now.",
    paymentMethodNotEnabledBankTransfer: "Bank transfer is not enabled right now.",
    cardPaymentNotAvailable: "Card payment is not available right now.",
    orderConfirmed: "Your order has been confirmed!",
    orderStatus_pending: "Pending",
    orderStatus_processing: "Processing",
    orderStatus_delivered: "Delivered",
    orderStatus_cancel: "Canceled",
    paymentFailed: "Payment failed.",
    noOrdersYet: "You have no orders yet!",
    brand: "Brand",
    popularBrands: "Popular Brands",
    topRatedProducts: "Top Rated Products",
    filterByColor: "Filter by Color",
    addToCart: "Add to Cart",
    viewCart: "View Cart",
    addToWishlist: "Add to Wishlist",
    addToCompare: "Add to Compare",
    quickView: "Quick View",
    addedToCartToast: "{quantity} {title} added to cart",
    removedFromCartToast: "{title} removed from cart",
    noMoreQuantityAvailable: "No more quantity available for this product!",
    confirmClearCart: "Are you sure you want to remove all items?",
    addedToWishlistToast: "{title} added to wishlist",
    removedFromWishlistToast: "{title} removed from wishlist",
    addedToCompareToast: "{title} added to compare",
    removedFromCompareToast: "{title} removed from compare",
    compareProducts: "Compare",
    buyNow: "Buy Now",
    quantity: "Quantity",
    color: "Color",
    reviews: "Reviews",
    review: "Review",
    seeMore: "See more",
    seeLess: "See less",
    outOfStock: "Out of stock",
    inStock: "In stock",
    onlyXLeft: "Only {count} left",
    askQuestion: "Ask a question",
    subtotal: "Subtotal",
    shipping: "Shipping",
    shippingCost: "Shipping Cost",
    discount: "Discount",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout",
    freeShipping: "Free shipping",
    securePayment: "Secure payment",
    flatRate: "Flat rate",
    localPickup: "Local pickup",
    cartEmpty: "Your cart is empty",
    wishlistEmpty: "Your wishlist is empty",
    compareEmpty: "Your compare list is empty",
    clearCart: "Clear Cart",
    goToShop: "Go to Shop",
    addMoreForFreeShipping: "Add {amount} more to qualify for free shipping",
    eligibleForFreeShipping: "You are eligible for free shipping",
    yourOrder: "Your Order",
    product: "Product",
    description: "Description",
    price: "Price",
    rating: "Rating",
    messageLabel: "Message",
    subjectLabel: "Subject",
    subjectRequired: "Subject is required",
    messageRequired: "Message is required",
    fullNamePlaceholder: "Full name",
    subjectPlaceholder: "Enter a subject",
    messagePlaceholder: "Write your message here...",
    consentText: "I agree to store my information in this browser for future use.",
    consentRequired: "Consent is required",
    sendMessageSuccess: "Message sent successfully",
    remove: "Remove",
    action: "Action",
    noDescription: "No description available",
    amount: "Amount",
    orderId: "Order Id",
    orderTime: "Order Time",
    view: "View",
    invoice: "Invoice",
    paymentMethod: "Payment Method",
    noPaymentMethodsEnabled: "No payment methods are currently enabled.",
    paypalPaymentNote: "Payment will be confirmed via PayPal after the order is created.",
    bankTransferManualPayment: "Bank transfer / manual payment",
    shippingOptionRequired: "Shipping option is required",
    paymentOptionRequired: "Payment option is required",
    cashOnDelivery: "Cash on Delivery",
    creditCard: "Credit Card",
    placeOrder: "Place Order",
    deliveryToday: "Delivery: Today Cost",
    deliverySevenDays: "Delivery: 7 Days Cost",
    deliveryEstimate: "Delivery estimate",
    deliveryEstimateDaysRange: "{min}–{max} days",
    giftWrap: "Gift Wrap",
    addGiftWrap: "Add gift wrap",
    giftWrapStandard: "Standard wrap",
    giftWrapPremium: "Premium wrap",
    giftWrapMessagePlaceholder: "Write a short gift message (optional)",
    giftWrapFee: "Gift wrap fee",
    bundleDiscount: "Bundle discount",
    quickConsultation: "Quick consultation on WhatsApp",
    featuredReviews: "Featured reviews",
    customer: "Customer",
    sizeGuide: "Size guide",
    sizeGuideRingTitle: "Ring",
    sizeGuideRingDesc: "Measure your finger circumference with a string/paper strip, note the mm, then match it to a size chart. If between sizes, choose the larger.",
    sizeGuideBraceletTitle: "Bracelet",
    sizeGuideBraceletDesc: "Measure your wrist and add 1–2 cm for comfort. Choose closer for a snug fit, add more for a looser fit.",
    sizeGuideNecklaceTitle: "Necklace",
    sizeGuideNecklaceDesc: "Pick the length based on style: 40–45 cm sits near the neck, 50–60 cm sits on the chest. Use a string to preview.",
    askAboutSize: "Ask about size",
    askAboutMaterial: "Ask about material",
    askAboutAvailability: "Ask about availability",
    whatsappQuestionGeneral: "I need a quick consultation about this product.",
    whatsappQuestionSize: "I need help choosing the right size.",
    whatsappQuestionMaterial: "What is the material / gold type / plating?",
    whatsappQuestionAvailability: "Is this item available now? What is the preparation time?",
    coupon: "Coupon",
    apply: "Apply",
    couponCode: "Coupon Code",
    haveCoupon: "Have a coupon?",
    clickToEnterCode: "Click here to enter your code",
    search: "Search",
    searchByLabel: "Search by",
    allDepartments: "All Departments",
    freeExpressShipping: "FREE Express Shipping On Orders {amount}+",
    footerDesc: "Azad Advanced Systems — a modern platform for a secure, smooth shopping experience.",
    myAccount: "My Account",
    personalDetails: "Personal Details",
    enterUsername: "Enter your username",
    enterYourEmail: "Enter your email",
    enterYourNumber: "Enter your number",
    enterYourAddress: "Enter your address",
    enterYourBio: "Enter your bio",
    updateProfile: "Update Profile",
    updateProfileFailed: "Failed to update profile",
    phoneMin11: "Phone must be at least 11 digits",
    bioMin20: "Bio must be at least 20 characters",
    oldPassword: "Old Password",
    newPassword: "New Password",
    oldPasswordRequired: "Old password is required",
    newPasswordRequired: "New password is required",
    changePasswordFailed: "Failed to change password",
    update: "Update",
    trackOrders: "Track Orders",
    shippingPolicy: "Shipping",
    orderHistory: "Order History",
    returns: "Returns",
    info: "Information",
    ourStory: "Our Story",
    careers: "Careers",
    privacyPolicy: "Privacy Policy",
    terms: "Terms & Conditions",
    whatsapp: "WhatsApp",
    facebook: "Facebook",
    sendMessage: "Send a Message",
    stayInTouch: "Stay in touch",
    followUsOnSocialMedia: "Follow us on social media",
    aboutIntro: "Azad Advanced Systems is a platform delivering carefully selected products with a secure, smooth purchasing experience. We focus on quality, customer care, and continuous improvements.",
    aboutVisionTitle: "Our Vision",
    aboutVisionDesc: "To be your preferred online shopping destination by providing a wide selection and reliable service.",
    aboutValuesTitle: "Our Values",
    aboutValue1: "Transparency and clarity in pricing and policies.",
    aboutValue2: "Quality in products, packaging, and delivery.",
    aboutValue3: "Fast, professional support when needed.",
    aboutContactPrefix: "For any questions or suggestions, feel free to reach out via our",
    aboutContactLink: "Contact page",
    contactPage: "Contact page",
    careersIntro: "We’re always looking for passionate people to improve the shopping experience and customer support. If you’d like to join our team, send your CV and area of interest.",
    careersHowToApplyTitle: "How to apply",
    careersStep1: "Use the email subject: “Careers - {siteName}”.",
    careersStep2: "Attach your CV and a portfolio link if available.",
    careersStep3: "Include your city, availability, and expertise.",
    careersContactTitle: "Contact",
    careersContactPrefix: "Send your application via",
    privacyIntro: "This Privacy Policy explains how we collect, use, and protect your information when you use the {siteName} website. By using the website, you agree to the practices described below.",
    privacyInfoWeCollectTitle: "Information we collect",
    privacyInfoWeCollect1: "Account information: name, email, phone number.",
    privacyInfoWeCollect2: "Order information: products, shipping address, invoice details.",
    privacyInfoWeCollect3: "Technical information: IP address, browser type, usage logs.",
    privacyHowWeUseTitle: "How we use your information",
    privacyHowWeUse1: "Process and confirm orders and provide after-sales service.",
    privacyHowWeUse2: "Contact you regarding orders or support requests.",
    privacyHowWeUse3: "Improve user experience and site performance.",
    privacySharingTitle: "Sharing information",
    privacySharingDesc: "We do not sell your personal information. We may share limited data with trusted providers (such as shipping or payment partners) as needed to deliver the service.",
    privacySecurityTitle: "Data security",
    privacySecurityDesc: "We apply appropriate security measures to help protect your data; however, complete security over the internet cannot be guaranteed.",
    privacyRightsTitle: "Your rights",
    privacyRightsPrefix: "You can request updates or deletion of your account data, or inquire about your data via our",
    returnsIntro: "Your satisfaction matters. This policy explains the conditions and steps for returns and exchanges.",
    returnsConditionsTitle: "Return conditions",
    returnsCondition1: "Items must be unused and in original condition.",
    returnsCondition2: "Please keep the invoice or order number.",
    returnsCondition3: "Some items may be excluded depending on their nature.",
    returnsStepsTitle: "How to request a return/exchange",
    returnsStep1: "Contact us with your order number and the reason.",
    returnsStep2: "We will provide shipping/delivery instructions based on the case.",
    returnsStep3: "After receiving and inspecting the item, the return or exchange is completed.",
    returnsRefundTitle: "Refunds",
    returnsRefundDesc: "Refunds are processed according to the original payment method after approval. Processing may take several business days depending on the payment provider.",
    returnsContactTitle: "Contact",
    returnsContactPrefix: "To start a return/exchange request, use the",
    shippingIntro: "We aim to ship orders as quickly as possible. This policy explains order processing and shipping/delivery options.",
    shippingPreparationTitle: "Order processing",
    shippingPreparation1: "Orders are prepared after payment confirmation.",
    shippingPreparation2: "Processing time may vary depending on availability and order volume.",
    shippingDeliveryTimesTitle: "Delivery times",
    shippingDeliveryTimes1: "Time estimates vary by region.",
    shippingDeliveryTimes2: "Delays may occur due to logistics or weather.",
    shippingCostTitle: "Shipping cost",
    shippingCostDesc: "Shipping cost (if any) is shown at checkout based on address and delivery method.",
    shippingTrackTitle: "Track your order",
    shippingTrackPrefix: "You can track your order status from your",
    shippingTrackLink: "account",
    termsIntro: "These Terms & Conditions govern your use of the {siteName} website and purchases made through it. By using the website or placing an order, you agree to these terms.",
    termsOrdersPaymentTitle: "Orders and payment",
    termsOrdersPayment1: "An order may be cancelled if payment cannot be confirmed or an item is unavailable.",
    termsOrdersPayment2: "Prices may change; the final price is confirmed when the order is placed.",
    termsShippingDeliveryTitle: "Shipping and delivery",
    termsShippingDeliveryDescPrefix: "Delivery times are estimates and may vary by region and operating conditions. For details, see the",
    termsReturnsTitle: "Returns and exchanges",
    termsReturnsDescPrefix: "Returns and exchanges follow the applicable policy. See the",
    termsIpTitle: "Intellectual property",
    termsIpDesc: "All content (text, images, logos) is owned by or licensed to Azad Advanced Systems and may not be used without permission.",
    termsContactTitle: "Contact",
    termsContactPrefix: "For questions about these terms, reach out via our",
    latestNews: "Latest News",
    contactUsSmall: "Contact Us",
    haveQuestionCall: "Have a question? Call us",
    copyright: "© {year} Azad Advanced Systems",
    addressLocation: "Ramallah, Palestine",
    share: "Share:",
    easyReturns: "30 days easy returns",
    sameDayDispatch: "Order before 2:30pm for same day dispatch",
    secureCheckoutLine1: "Guaranteed safe",
    secureCheckoutLine2: "& secure checkout",
    subscribe: "Subscribe",
    subscribeDesc: "Subscribe to receive the latest deals and products.",
    enterEmail: "Enter your email",
    followUsOn: "Follow us on",
    pageNotFoundTitle: "Oops! Page not found",
    pageNotFoundDesc: "The page you were looking for was not found.",
    backToHome: "Back to Home",
    dealOfDay: "Deal of The Day",
    viewAllDeals: "View All Deals",
    productCollection: "Product Collection",
    discoverOurProducts: "Discover our Products",
    viewNow: "View Now",
    products: "Products",
    allCollection: "All Collection",
    bracelets: "Bracelets",
    necklaces: "Necklaces",
    earrings: "Earrings",
    withNewLookCollection: "WITH NEW LOOK & NEW COLLECTION",
    spotlightProductTitle: "Featured Product",
    spotlightProductDesc: "Explore the details inside the collection.",
    buildYourOwnSets: "BUILD YOUR OWN SETS",
    ourFinestJewelry: "Our finest jewelry",
    shopThisCollection: "Shop this collection",
    bestSellerThisWeek: "Best Seller This Week’s",
    weeksFeatured: "This Week's Featured",
    shopAllProducts: "Shop All Products",
    moreToDiscover: "More to Discover",
    trendingArrivals: "Trending Arrivals",
    trendingBannerTitleLine1: "Short Sleeve Tunic",
    trendingBannerTitleLine2: "Tops Casual Swing",
    exploreMore: "Explore More",
    newArrivalsTitle: "New Arrivals",
    trendingProducts: "Trending Products",
    tabNew: "New",
    tabFeatured: "Featured",
    tabTopSellers: "Top Sellers",
    trendingThisWeek: "Trending This Week’s",
    specialProducts: "Special products",
    enjoyBestQuality: "Enjoy the best quality",
    tabTrending: "Trending",
    tabBeauty: "Beauty",
    tabCosmetics: "Cosmetics",
    topSellersForYou: "Top Sellers For You",
    bestSellersInBeauty: "Best sellers in beauty",
    shopByFeatured: "Shop by Featured",
    discountProducts: "Discount Products",
    featuredProducts: "Featured Products",
    sellingProducts: "Selling Products",
    selectedNoveltyLine1: "Selected novelty",
    selectedNoveltyLine2: "Products",
    topRatedLine1: "Top Rated",
    topRatedLine2: "Products",
    onlyPrice: "Only {price}",
    electronicsGadgetsLine1: "Electronics",
    electronicsGadgetsLine2: "Gadgets",
    moreProducts: "More Products",
    sale20OffAllStore: "Sale 20% off all store",
    sale35Off: "Sale 35% off",
    subscribeNewsletter: "Subscribe our Newsletter",
    bannerSmartphoneLine1: "Smartphone",
    bannerSmartphoneLine2: "BLU G91 Pro 2022",
    bannerHyperXLine1: "HyperX Cloud II",
    bannerHyperXLine2: "Wireless",
    startingAt: "Starting at",
    bestTabletCollection2023: "The best tablet Collection 2023",
    bestNotebookCollection2023: "The best note book collection 2023",
    exclusiveOffer: "Exclusive offer",
    offThisWeek: "off this week",
    palHeroBadge1: "New Collection",
    palHeroBadge2: "Limited Drop",
    palHeroBadge3: "Gifts from the heart",
    palHeroTitle1: "Gold that fits you",
    palHeroTitle2: "Keffiyeh story, modern spirit",
    palHeroTitle3: "A gift with meaning",
    palHeroText1a: "Inspired by",
    palHeroText1b: "Palestine",
    palHeroText1c: "with a global design",
    palHeroText2a: "Fine details,",
    palHeroText2b: "authenticity",
    palHeroText2c: "on-trend",
    palHeroText3a: "Elegant wrapping with a",
    palHeroText3b: "red",
    palHeroText3c: "accent that stands out",
    nextDayProducts: "Next day Products",
    relatedProducts: "Related Products",
    bundleSubtitle: "Complete your look",
    completeYourLook: "Build your set",
    bundleDiscountHint: "Bundle discount: {percent}% when you buy {minItems}+ items (applied at checkout)",
    faqShippingQuestion: "How long does delivery take?",
    faqShippingAnswer: "Delivery typically takes {min}–{max} business days depending on your area and availability.",
    faqReturnsQuestion: "Do you offer returns or exchanges?",
    faqReturnsAnswer: "Yes — returns/exchanges are available within {days} days per store policy.",
    faqSizeQuestion: "How do I choose the right size?",
    faqSizeAnswer: "Use the size guide on the product page, or contact us on WhatsApp for help.",
    recentlyViewedSubtitle: "Recently viewed",
    recentlyViewed: "Recently viewed products",
    collection: "Collection",
    collections: "Collections",
    collectionsSubtitle: "Browse our curated drops",
    collectionsTitle: "Shop collections",
    trending: "Trending",
    newArrival: "New Arrival",
    jewelryBannerTitle1Line1: "Ardeco pearl",
    jewelryBannerTitle1Line2: "Rings style 2023",
    jewelryBannerTitle2: "Tropical Set",
    jewelryBannerTitle3: "Gold Jewelry",
    jewelryBannerFullTitleLine1: "Ring gold with",
    jewelryBannerFullTitleLine2: "diamonds",
    cosmeticsCollection: "Cosmetics Collection",
    foundationAndPowderBrushLine1: "Foundation and",
    foundationAndPowderBrushLine2: "powder brush",
    discoverNow: "Discover Now",
    topsBlouseShirtsLine1: "Tops",
    topsBlouseShirtsLine2: "Blouse Shirts",
    shopCollection: "Shop Collection",
    beautySelectionOffer: "Discover our Beauty Selection {discount} for your...",
    beautySelectionDiscount: "75% Extra Discount",
    day: "Day",
    hrs: "Hrs",
    min: "Min",
    sec: "Sec",
    flashSaleEndsIn: "Flash Sale end in:",
    off: "Off",
    active: "Active",
    inactive: "Inactive",
    copied: "Copied!",
    couponTooltipPart1: "*This coupon code will apply on",
    couponTooltipCategory: "Grocery type products",
    couponTooltipPart2: "and when you shop more than",
    sku: "SKU",
    tag: "Tag",
    twitter: "Twitter",
    linkedin: "LinkedIn",
    vimeo: "Vimeo",
    paymentOptions: "Payment options",
    orderDetails: "Order Details",
    invoiceId: "Invoice ID",
    date: "Date",
    serial: "No.",
    print: "Print",
    thankYouOrderReceived: "Thank you {name}, your order has been received!",
    authenticityCardTitle: "Authenticity Card",
    authenticityQrAlt: "Authenticity verification QR code",
    scanToVerifyOnWhatsapp: "Scan the QR code to verify on WhatsApp",
    verifyOnWhatsapp: "Verify on WhatsApp",
    authenticityWhatsappMessage: "Hi, I'd like to verify the authenticity of order invoice #{invoice}.",
    reviewsAreIn: "The Reviews Are In",
    customersReview: "Customers Review",
    whatClientsSay: "What our clients say",
    coFounder: "Co-Founder",
    uiUxDesigner: "UI/UX Designer",
    webDeveloper: "Web Developer",
    fashionTestimonial1: "“How you use the city or town name is up to you. All results may be freely used in any work.”",
    fashionTestimonial2: "“Very happy with our choice. The entire team was great! Thank you!”",
    fashionTestimonial3: "“Thanks for all your efforts and teamwork over the last several months! Thank you so much.”",
    beautyTestimonial1: "Great experience, high quality, and fast service. Highly recommended.",
    beautyTestimonial2: "Beautiful products and details with a smooth shopping experience.",
    beautyTestimonial3: "Elegant packaging, secure checkout, and fast delivery. Excellent experience.",
  },
};

const LanguageContext = createContext({
  language: "ar",
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => key,
  currency: "ILS",
  setCurrency: () => {},
  formatPrice: (value) => value,
  currencyLabel: () => "",
});

const getInitialLanguage = () => {
  if (typeof window === "undefined") {
    return "ar";
  }
  const stored = localStorage.getItem("appLanguage");
  if (stored === "ar" || stored === "en") {
    return stored;
  }
  const browserLang = navigator.language?.toLowerCase() || "";
  return browserLang.startsWith("ar") ? "ar" : "en";
};

export const translate = (key, vars = {}, languageOverride) => {
  const language = languageOverride || getInitialLanguage();
  const template = translations[language]?.[key] || translations.en[key] || key;
  return Object.keys(vars).reduce(
    (result, varKey) => result.replaceAll(`{${varKey}}`, vars[varKey]),
    template
  );
};

const currencyMeta = {
  ILS: { code: "ILS", rate: 3.65 },
  JOD: { code: "JOD", rate: 0.71 },
  USD: { code: "USD", rate: 1 },
  AED: { code: "AED", rate: 3.67 },
  SAR: { code: "SAR", rate: 3.75 },
};

const getInitialCurrency = () => {
  if (typeof window === "undefined") {
    return "ILS";
  }
  const stored = localStorage.getItem("appCurrency");
  if (stored && currencyMeta[stored]) {
    return stored;
  }
  return "ILS";
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getInitialLanguage);
  const [currency, setCurrency] = useState(getInitialCurrency);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    localStorage.setItem("appLanguage", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    localStorage.setItem("appCurrency", currency);
  }, [currency]);

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => (prev === "ar" ? "en" : "ar"));
  }, []);

  const t = useCallback(
    (key, vars = {}) => {
      const template = translations[language]?.[key] || translations.en[key] || key;
      return Object.keys(vars).reduce(
        (result, varKey) => result.replaceAll(`{${varKey}}`, vars[varKey]),
        template
      );
    },
    [language]
  );

  const formatPrice = useCallback(
    (value) => {
      const numericValue = Number(value);
      if (Number.isNaN(numericValue)) {
        return value;
      }
      const meta = currencyMeta[currency] || currencyMeta.ILS;
      const locale = language === "ar" ? "ar" : "en";
      return new Intl.NumberFormat(locale, {
        style: "currency",
        currency: meta.code,
        maximumFractionDigits: 2,
      }).format(numericValue * meta.rate);
    },
    [currency, language]
  );

  const currencyLabel = useCallback(
    (code) => {
      switch (code) {
        case "ILS":
          return t("currencyILS");
        case "JOD":
          return t("currencyJOD");
        case "USD":
          return t("currencyUSD");
        case "AED":
          return t("currencyAED");
        case "SAR":
          return t("currencySAR");
        default:
          return code;
      }
    },
    [t]
  );

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage,
      t,
      currency,
      setCurrency,
      formatPrice,
      currencyLabel,
    }),
    [language, setLanguage, toggleLanguage, t, currency, setCurrency, formatPrice, currencyLabel]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
